### ISSUE TITLE
Server Crash - Deep Resonance Tank?

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#15]
Possibly a deep resonance issue?

## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: 12.18.3.2281
* TolkienCraft II version: 0.9.6

Had a large tinkers tank partially filled with creosote from a coke oven, a transfer node ( liquid ) pulling out of the tinkers tank and putting the creosote into a deep resonance tank.  Worked awesome while in the world and the location with the setup, easy access to the creosote.  

Left things setup with creosote in the tinkers tank and the deep resonance tank full.  Left the base & dimension and upon returning to the location with above setup, presumably when the server tried to load the chunk that contained the above setup, the server would crash.  At that point was unable to log back into the world as a login would put me in a location that would load the chunk and crash the server.  Ended up having to edit the world, deleted both the tank and the transfer node, everything back to stable.

## Crash report
```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
  Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  LoadingPlugin (Quark-r1.1-70.jar)
  ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  llibrary (llibrary-1.7.4-1.10.2.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  CorePlugin (MrTJPCore-1.10.2-2.0.0.17-universal.jar)
  PSLoadingPlugin (PerfectSpawn-MC1.10.2-1.4.jar)
Contact their authors BEFORE contacting forge

// I'm sorry, Dave.

Time: 5/9/17 5:58 PM
Description: Exception ticking world entities

java.lang.NullPointerException: Exception ticking world entities
	at java.util.Objects.requireNonNull(Unknown Source)
	at java.util.Optional.<init>(Unknown Source)
	at java.util.Optional.of(Unknown Source)
	at mcjty.deepresonance.blocks.tank.TileTank.onTileUnloaded(TileTank.java:170)
	at mcjty.deepresonance.blocks.tank.TileTank.func_145843_s(TileTank.java:151)
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:816)
	at net.minecraft.world.World.func_72939_s(World.java:1872)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.util.Objects.requireNonNull(Unknown Source)
	at java.util.Optional.<init>(Unknown Source)
	at java.util.Optional.of(Unknown Source)
	at mcjty.deepresonance.blocks.tank.TileTank.onTileUnloaded(TileTank.java:170)
	at mcjty.deepresonance.blocks.tank.TileTank.func_145843_s(TileTank.java:151)
	at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:816)
	at net.minecraft.world.World.func_72939_s(World.java:1872)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)

-- Affected level --
Details:
	Level name: world
	All players: 1 total; [EntityPlayerMP['4sheets_captain'/242, l='world', x=1072.39, y=84.00, z=511.68]]
	Chunk stats: ServerChunkCache: 442 Drop: 0
	Level seed: 2438652705890004143
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (14911,143,5960), Chunk: (at 15,8,8 in 931,372; contains blocks 14896,0,5952 to 14911,255,5967), Region: (29,11; contains chunks 928,352 to 959,383, blocks 14848,0,5632 to 15359,255,6143)
	Level time: 37887109 game time, 1561 day time
	Level dimension: 50
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 30904 (now: false), thunder time: 24488 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Linux (amd64) version 3.11.10-100.fc18.x86_64
	Java Version: 1.8.0_121, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 2604662472 bytes (2483 MB) / 4214489088 bytes (4019 MB) up to 8509456384 bytes (8115 MB)
	JVM Flags: 16 total; -Xms4096m -Xmx8192m -Xmn768m -XX:PermSize=256m -XX:TargetSurvivorRatio=80 -XX:MaxTenuringThreshold=15 -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:+DisableExplicitGC -XX:MaxGCPauseMillis=40 -XX:GCPauseIntervalMillis=150 -XX:+AggressiveOpts -XX:+TieredCompilation -XX:ReservedCodeCacheSize=2048m -XX:+UseCodeCacheFlushing -XX:CompileThreshold=1000
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.3.2281 101 mods loaded, 101 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	Forge{12.18.3.2281} [Minecraft Forge] (forge-1.10.2-12.18.3.2281-universal.jar) 
	UCHIJAAAA	Aroma1997Core{${version}} [Aroma1997Core] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	<CoFH ASM>{000} [CoFH ASM] (minecraft.jar) 
	UCHIJAAAA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJAAAA	AkashicTome{1.0-5} [Akashic Tome] (AkashicTome-1.0-5.jar) 
	UCHIJAAAA	allomancy{2.2.1} [Allomancy] (allomancy-2.2.1.jar) 
	UCHIJAAAA	antiqueatlas{1.9.4-4.3.0} [Antique Atlas] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJAAAA	AntiqueAtlasOverlay{1.2} [AntiqueAtlasOverlay] (antiqueatlas-1.9.4-4.3.0.jar) 
	UCHIJAAAA	architecturecraft{1.7.1} [ArchitectureCraft] (ArchitectureCraft-1.7.1-mc1.10.2.jar) 
	UCHIJAAAA	Aroma1997CoreHelper{1.1.1.2} [Aroma1997Core|Helper] (Aroma1997Core-1.9.4-1.1.1.2.jar) 
	UCHIJAAAA	AromaBackup{1.0.1.1} [AromaBackup] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	AromaBackupRecovery{1.0} [AromaBackup Recovery] (AromaBackup-1.9.4-1.0.1.1.jar) 
	UCHIJAAAA	arsmagica2{1.5.018} [Ars Magica 2] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAA	AnimationAPI{1.2.4} [AnimationAPI] (ArsMagica2-1.10.2-1.5.0-18.jar) 
	UCHIJAAAA	atlcraft{1.10.2-Ver1.5} [ATLCraft Candles Mod] (ATLCraftCandlesMod(MC1.10.2-Ver1.5).jar) 
	UCHIJAAAA	Morphtool{1.0-12} [Morph-o-Tool] (Morph-o-Tool-1.0-12.jar) 
	UCHIJAAAA	Quark{r1.1-70} [Quark] (Quark-r1.1-70.jar) 
	UCHIJAAAA	AutoRegLib{1.0-2} [AutoRegLib] (AutoRegLib-1.0-2.jar) 
	UCHIJAAAA	BetterAchievements{0.3.3.10} [Better Achievements] (BetterAchievements-1.10.2-0.3.3.10.jar) 
	UCHIJAAAA	betteragriculture{1.0.1} [Better Agriculture] (BetterAgriculture-[1.10.2]-1.0.1.jar) 
	UCHIJAAAA	betterquesting{2.3.225} [Better Questing] (BetterQuesting-2.3.225.jar) 
	UCHIJAAAA	bqt{0.9} [Better Questing Triggerer] (BetterQuestingTriggerer-0.9.jar) 
	UCHIJAAAA	BiblioCraft{2.2.1} [BiblioCraft] (BiblioCraft[v2.2.1][MC1.10.2].jar) 
	UCHIJAAAA	birdsnests{1.5.1} [Bird's Nests] (BirdsNests1.10-1.5.1.jar) 
	UCHIJAAAA	guideapi{@VERSION@} [Guide-API] (Guide-API-1.10.2-2.0.3-46.jar) 
	UCHIJAAAA	JEI{3.14.7.419} [Just Enough Items] (jei_1.10.2-3.14.7.419.jar) 
	UCHIJAAAA	BloodMagic{1.10.2-2.1.9-78} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.10.2-2.1.9-78.jar) 
	UCHIJAAAA	infinitylib{1.10.2-0.8.0} [InfinityLib] (infinitylib-0.8.0.jar) 
	UCHIJAAAA	boatlantern{1.10.2-0.4.0} [Lantern] (boatlantern-0.4.0.jar) 
	UCHIJAAAA	bqmie{1.0.0} [BQMIE] (BQMIE-1.10.2-1.0.0.1-universal.jar) 
	UCHIJAAAA	CodeChickenLib{2.5.8.255} [CodeChicken Lib] (CodeChickenLib-1.10.2-2.5.8.255-universal.jar) 
	UCHIJAAAA	cofhcore{4.1.1} [CoFH Core] (CoFHCore-1.10.2-4.1.1.156-universal.jar) 
	UCHIJAAAA	brandonscore{2.1.6} [Brandon's Core] (BrandonsCore-1.10.2-2.1.6.98-universal.jar) 
	UCHIJAAAA	Chameleon{1.10-2.2.2} [Chameleon] (Chameleon-1.10-2.2.2.jar) 
	UCHIJAAAA	CodeChickenCore{2.4.1.102} [CodeChicken Core] (CodeChickenCore-1.10.2-2.4.1.102-universal.jar) 
	UCHIJAAAA	ChickenChunks{2.2.0.52} [ChickenChunks] (ChickenChunks-1.10.2-2.2.0.52-universal.jar) 
	UCHIJAAAA	chisel{MC1.10.2-0.0.10.22} [Chisel] (Chisel-MC1.10.2-0.0.10.22.jar) 
	UCHIJAAAA	chiselsandbits{12.12} [Chisels & Bits] (chiselsandbits-12.12.jar) 
	UCHIJAAAA	craftingtweaks{6.1.16} [Crafting Tweaks] (CraftingTweaks_1.10.2-6.1.16.jar) 
	UCHIJAAAA	crashlogadditions{1.1} [Crash Log Additions] (CrashLogAdditions-1.10.2-1.1.jar) 
	UCHIJAAAA	customnpcs{1.10.2} [CustomNPCs] (CustomNPCs_1.10.2(17mar17).jar) 
	UCHIJAAAA	customstartinggear{1.0.0} [Custom Starting Gear] (CustomStartingGear-1.10.2-1.0.0.7-universal.jar) 
	UCHIJAAAA	PTRModelLib{1.0.0} [PTRModelLib] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJAAAA	props{2.4.2} [Decocraft] (Decocraft-2.4.2_1.10.2.jar) 
	UCHIJAAAA	forestry{5.2.17.376} [Forestry] (forestry_1.10.2-5.2.17.376.jar) 
	UCHIJAAAA	eleccore{1.7.418} [ElecCore] (ElecCore-1.10.2-1.7.418.jar) 
	UCHIJAAAA	deepresonance{1.4.7} [DeepResonance] (deepresonance-1.1x-1.4.7.jar) 
	UCHIJAAAA	draconicevolution{2.0.10} [Draconic Evolution] (Draconic-Evolution-1.10.2-2.0.10.199-universal.jar) 
	UCHIJAAAA	embers{0.104} [Embers] (embers-0.104.jar) 
	UCHIJAAAA	EnderStorage{2.2.1.106} [EnderStorage] (EnderStorage-1.10.2-2.2.1.106-universal.jar) 
	UCHIJAAAA	expandablebackpack{1.1} [Expandable Backpacks] (expandableBackpacks1.1.10-1.10.2.jar) 
	UCHIJAAAA	extrautils2{1.0} [Extra Utilities 2] (extrautils2-1.10.2-1.4.1.jar) 
	UCHIJAAAA	FastLeaveDecay{1.2.3} [Fast Leave Decay] (FastLeaveDecay-MC1.10.2-1.2.3.jar) 
	UCHIJAAAA	flatcoloredblocks{mc1.10-v4.4} [Flat Colored Blocks] (flatcoloredblocks-mc1.10-v4.4.jar) 
	UCHIJAAAA	forgemultipartcbe{2.0.0.31} [Forge Multipart CBE] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAAAA	microblockcbe{2.0.0.31} [Forge Microblocks] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAAAA	minecraftmultipartcbe{2.0.0.31} [Minecraft Multipart Plugin] (ForgeMultipart-1.10.2-2.0.0.31-universal.jar) 
	UCHIJAAAA	Waila{1.8.13-B27_1.10.2} [Waila] (Hwyla-1.8.13-B27_1.10.2.jar) 
	UCHIJAAAA	llibrary{1.7.4} [LLibrary] (llibrary-1.7.4-1.10.2.jar) 
	UCHIJAAAA	iceandfire{1.0.1} [Ice and Fire] (iceandfire-1.0.1.jar) 
	UCHIJAAAA	mantle{1.10.2-1.1.5.205} [Mantle] (Mantle-1.10.2-1.1.5.jar) 
	UCHIJAAAA	tconstruct{1.10.2-2.6.3.500} [Tinkers' Construct] (TConstruct-1.10.2-2.6.3.jar) 
	UCHIJAAAA	immersiveengineering{0.10-57} [Immersive Engineering] (ImmersiveEngineering-0.10-57.jar) 
	UCHIJAAAA	ironchest{1.10.2-7.0.12.801} [Iron Chest] (ironchest-1.10.2-7.0.12.801.jar) 
	UCHIJAAAA	journeymap{1.10.2-5.4.6} [JourneyMap] (journeymap-1.10.2-5.4.6.jar) 
	UCHIJAAAA	justenoughdimensions{1.4.2} [Just Enough Dimensions] (justenoughdimensions-1.10.2-1.4.2.jar) 
	UCHIJAAAA	levelup{${version}} [Level Up!] (LevelUp!-0.12.9-1.10.2.jar) 
	UCHIJAAAA	lootbags{2.3.8} [Loot Bags] (LootBags-1.10.2-2.3.8.jar) 
	UCHIJAAAA	RadixCore{1.10.2-2.1.3} [RadixCore] (RadixCore-1.10.2-2.1.3-universal.jar) 
	UCHIJAAAA	MCA{1.10.2-5.2.3} [Minecraft Comes Alive] (MCA-1.10.2-5.2.3-universal.jar) 
	UCHIJAAAA	modularrouters{1.10.2-1.3.1} [Modular Routers] (modular-routers-1.10.2-1.3.1.jar) 
	UCHIJAAAA	MrTJPCoreMod{2.0.0.17} [MrTJPCore] (MrTJPCore-1.10.2-2.0.0.17-universal.jar) 
	UCHIJAAAA	bq_npc_integration{2.3.21} [NPC Integration] (NPCIntegration-2.3.21.jar) 
	UCHIJAAAA	harvestcraft{1.9.4-1.10.2g} [Pam's HarvestCraft] (Pam's HarvestCraft 1.9.4-1.10.2h.jar) 
	UCHIJAAAA	PerfectSpawn{1.4} [Perfect Spawn] (PerfectSpawn-MC1.10.2-1.4.jar) 
	UCHIJAAAA	projectred-core{4.8.1.30} [ProjectRed Core] (ProjectRed-1.10.2-4.8.1.30-Base.jar) 
	UCHIJAAAA	projectred-integration{4.8.1.30} [ProjectRed integration] (ProjectRed-1.10.2-4.8.1.30-integration.jar) 
	UCHIJAAAA	projectred-transmission{4.8.1.30} [ProjectRed Transmission] (ProjectRed-1.10.2-4.8.1.30-integration.jar) 
	UCHIJAAAA	railcraft{10.1.1} [Railcraft] (Railcraft_1.10.2-10.1.1.jar) 
	UCHIJAAAA	xreliquary{1.10.2-1.3.3.659} [Reliquary] (Reliquary-1.10.2-1.3.3.659.jar) 
	UCHIJAAAA	corerm{1.2e-1.9.4} [RikMuld's Core] (RikMuldsCore_1.2e-1.10.2.jar) 
	UCHIJAAAA	roots{0.208} [Roots] (roots-0.208.jar) 
	UCHIJAAAA	bq_standard{2.3.131} [Standard Expansion] (StandardExpansion-2.3.131.jar) 
	UCHIJAAAA	StorageDrawers{1.10.2-3.7.3} [Storage Drawers] (StorageDrawers-1.10.2-3.7.3.jar) 
	UCHIJAAAA	camping{2.3d-1.9.4} [The Camping Mod 2] (TheCampingMod_2.3d-1.10.2.jar) 
	UCHIJAAAA	thermalfoundation{2.0.5} [Thermal Foundation] (ThermalFoundation-1.10.2-2.0.5.81-universal.jar) 
	UCHIJAAAA	thut_wearables{1.1.2} [Thut's Wearables] (thut_wearables-1.1.2.jar) 
	UCHIJAAAA	thutcore{3.12.2} [ThutCore] (thutcore-3.12.2.jar) 
	UCHIJAAAA	thut_bling{1.0.1} [Thut's Bling] (thut_bling-1.0.1.jar) 
	UCHIJAAAA	tinkertoolleveling{1.10.2-1.0.1.DEV.f5def58} [Tinkers Tool Leveling] (TinkerToolLeveling-1.10.2-1.0.1.jar) 
	UCHIJAAAA	tolkientweaks{2.0.1} [Tolkien Tweaks] (TolkienTweaks-1.10.2-2.0.1.16-universal.jar) 
	UCHIJAAAA	TownBuilder{1.0.0-Build8} [Town Builder] (TownBuilder-1.10.2-2.0.0.1-universal.jar) 
	UCHIJAAAA	Translocator{2.1.4.55} [Translocator] (Translocators-1.10.2-2.1.4.55-universal.jar) 
	UCHIJAAAA	VeinMiner{0.35.3_1.9-a46c1b0} [Vein Miner] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	VeinMinerModSupport{0.35.3_1.9-a46c1b0} [Mod Support] (VeinMiner-1.9-0.35.3.595+a46c1b0.jar) 
	UCHIJAAAA	icse{1.1.0.0} [I Can See Everything] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wawla{2.3.2.215} [What Are We Looking At] (Wawla-1.10.2-2.3.2.215.jar) 
	UCHIJAAAA	wolfarmor{1.3.1} [Wolf Armor and Storage] (wolfarmor-1.4.1.0.jar) 
	UCHIJAAAA	Woot{1.10.2-1.4.0} [Woot] (woot-1.10.2-1.4.0.jar) 
	Loaded coremods (and transformers): 
CoreMod (Aroma1997Core-1.9.4-1.1.1.2.jar)
  
Brandon's Core (BrandonsCore-1.10.2-2.1.6.98-universal.jar)
  com.brandon3055.brandonscore.asm.ClassTransformer
Default Options (DefaultOptions_1.10.2-6.1.5.jar)
  net.blay09.mods.defaultoptions.coremod.DefaultOptionsClassTransformer
IceAndFireForgeLoading (iceandfire-1.0.1.jar)
  com.github.alexthe666.iceandfire.access.IceAndFireTransformer
LoadingPlugin (Quark-r1.1-70.jar)
  vazkii.quark.base.asm.ClassTransformer
ChiselCorePlugin (Chisel-MC1.10.2-0.0.10.22.jar)
  team.chisel.common.asm.ChiselTransformer
llibrary (llibrary-1.7.4-1.10.2.jar)
  net.ilexiconn.llibrary.server.core.plugin.LLibraryTransformer
  net.ilexiconn.llibrary.server.core.patcher.LLibraryRuntimePatcher
CCLCorePlugin (CodeChickenLib-1.10.2-2.5.8.255-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.CCL_ASMTransformer
ArsMagica2-Preloader (ArsMagica2-1.10.2-1.5.0-18.jar)
  am2.asm.Transformer
CoFH Loading Plugin (CoFHCore-1.10.2-4.1.1.156-universal.jar)
  cofh.asm.CoFHClassTransformer
  cofh.asm.repack.codechicken.lib.asm.ClassHierarchyManager
CorePlugin (MrTJPCore-1.10.2-2.0.0.17-universal.jar)
  
PSLoadingPlugin (PerfectSpawn-MC1.10.2-1.4.jar)
  lumien.perfectspawn.asm.PSClassTransformer
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- craftingtweaksIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

	CodeChickenLib Invalid Fingerprint Reports: 
	CodeChickenCore Invalid Fingerprint Reports: 
	ChickenChunks Invalid Fingerprint Reports: 
	TolkienCraft III - Return to Middle-earth - 0.9.4: 
			30 years have passed
			and things are not well.

	EnderStorage Invalid Fingerprint Reports: 
	Translocator Invalid Fingerprint Reports: 
	Profiler Position: N/A (disabled)
	Player Count: 1 / 20; [EntityPlayerMP['4sheets_captain'/242, l='world', x=1072.39, y=84.00, z=511.68]]
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by GreatOrator** [comment]
Reported to McJty.

**Comment by GreatOrator** [comment]
He just released a new version a few minutes ago that should fix this if you want to manually update and see if the crash goes away.

I will be updating the pack tonight as well and push out a new version either tonight or tomorrow morning.

**Comment by timkrieger** [comment]
Tested with the updated version of deep resonance and can confirm that
it does indeed fix the crash I was experiencing.




On Wed, 2017-05-10 at 06:00 -0700, GreatOrator wrote:
> > He just released a new version a few minutes ago that should fix this
if you want to manually update and see if the crash goes away.
> > I will be updating the pack tonight as well and push out a new
version either tonight or tomorrow morning.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 
> 
>   
>   
> 
> 
> 
> 
> 
> 
> > > > > > > > > > > > > > > > > {"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c5
5493e4bb","name":"GitHub"},"entity":{"external_key":"github/GreatOrat
or/TolkienCraft-3-Map","title":"GreatOrator/TolkienCraft-3-
Map","subtitle":"GitHub repository","main_image_url":"https://cloud.g
ithubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-
7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent
.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-
b52498112777.png","action":{"name":"Open in
GitHub","url":"https://github.com/GreatOrator/TolkienCraft-3-
Map"}},"updates":{"snippets":[{"icon":"PERSON","message":"@GreatOrato
r in #15: He just released a new version a few minutes ago that
should fix this if you want to manually update and see if the crash
goes away.\r\n\r\nI will be updating the pack tonight as well and
push out a new version either tonight or tomorrow
morning."}],"action":{"name":"View
Issue","url":"https://github.com/GreatOrator/TolkienCraft-3-
Map/issues/15#issuecomment-300474483"}}}

**Comment by GreatOrator** [comment]
Perfect, it will be included with the pack update, thank you!
