### ISSUE TITLE
Quest book

### ISSUE THREAD

**Issue by timkrieger** [GreatOrator/TolkienCraft-3-Map#9]
## Base information
* Minecraft version: 1.10.2
* Minecraft Forge version: forge-1.10.2-12.18.3.2281
* TolkienCraft II version: 0.9.5

Probably not a bugs per se, but wanted to make sure it was known and/or expected behaviour.

Quest book not in starting inventory, was able to obtain one from Darage the Elven Recorder.
  - The Quest book does not show the background images on any pages ( see large black and purple squares )

**Comment by GreatOrator** [comment]
Interesting the images are not displaying, do they show up when you use the open book key? ("O" by default)

And yeah, I don't give the book to start since BQ actually has a key binding to open the quest book without an item.  I just put that in if players are more comfortable using an item to open the book.

**Comment by timkrieger** [comment]
Images still do not display if opened via the key.

**Comment by GreatOrator** [comment]
Go into your minecraft directory, configs, betterquesting, resources.  Check to see if the images are in the folders there.  No reason they should not load if the images are there otherwise it would have to be something with the loading causing them to not display.

**Comment by timkrieger** [comment]
Checked, both client and server, the images are there under the gui.

I noticed the pathing is \\ in the config file, running on linux client & server here but would not expect that to make a difference ( did try swapping these with single \ and single / no change ).  hunting for debug log settings to try for more helpful information.

**Comment by GreatOrator** [comment]
well, the config file should have the image paths listed, also believe the defaultquests file (or the quest database file) stores the design work such as the images.

**Comment by timkrieger** [comment]
I was able to get a log out of my client showing it was having issues finding the images, though they are clearly there when looking on the file system.  I don't have a windows system around to test on at this point I am suspecting it is related to either the linux desktops or the MultiMC client we are running the pack under.

Thanks for the help hunting the issue.  I'll update if I find a solution.


[18:15:50] [Client thread/WARN]: Failed to load texture: tolkiencraft:textures\gui\main_title.png
java.io.FileNotFoundException: tolkiencraft:textures\gui\main_title.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:34) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:79) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) [bwf.class:?]
	at betterquesting.client.gui.GuiHome.func_73863_a(GuiHome.java:79) [GuiHome.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at Reflector.callVoid(Reflector.java:512) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1409) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]
[18:15:55] [Client thread/WARN]: Failed to load texture: tolkiencraft:textures\gui\blankMEmap.png
java.io.FileNotFoundException: tolkiencraft:textures\gui\blankMEmap.png
	at net.minecraft.client.resources.FallbackResourceManager.func_110536_a(FallbackResourceManager.java:68) ~[bww.class:?]
	at net.minecraft.client.resources.SimpleReloadableResourceManager.func_110536_a(SimpleReloadableResourceManager.java:65) ~[bxi.class:?]
	at net.minecraft.client.renderer.texture.SimpleTexture.func_110551_a(SimpleTexture.java:34) ~[bwa.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110579_a(TextureManager.java:79) [bwf.class:?]
	at net.minecraft.client.renderer.texture.TextureManager.func_110577_a(TextureManager.java:49) [bwf.class:?]
	at betterquesting.client.gui.GuiQuestLinesEmbedded.drawBackground(GuiQuestLinesEmbedded.java:136) [GuiQuestLinesEmbedded.class:?]
	at betterquesting.api.client.gui.GuiScreenThemed.drawBackPanel(GuiScreenThemed.java:96) [GuiScreenThemed.class:?]
	at betterquesting.api.client.gui.GuiScreenThemed.func_73863_a(GuiScreenThemed.java:108) [GuiScreenThemed.class:?]
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:382) [ForgeHooksClient.class:?]
	at sun.reflect.GeneratedMethodAccessor24.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at Reflector.callVoid(Reflector.java:512) [Reflector.class:?]
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1409) [bnz.class:?]
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1076) [bcx.class:?]
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:371) [bcx.class:?]
	at net.minecraft.client.main.Main.main(SourceFile:124) [Main.class:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:236) [NewLaunch.jar:?]
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:297) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.listen(EntryPoint.java:162) [NewLaunch.jar:?]
	at org.multimc.EntryPoint.main(EntryPoint.java:53) [NewLaunch.jar:?]

**Comment by GreatOrator** [comment]
Oh, so you're on a linux system or mac?

**Comment by GreatOrator** [comment]
Going to report this to funwayguy and see if he can find out why, thank you for the log, that really helps.

**Comment by GreatOrator** [comment]
With the recent update, is this fixed or no?

**Comment by timkrieger** [comment]
Nope, still the same after the update to 0.9.6

Running server and clients on linux with Sun java 8 u121

**Comment by GreatOrator** [comment]
Well, waiting to hear back from funway on it.  Has to be something unique to linux and the way his book does the linking

**Comment by timkrieger** [comment]
Was able to get the main quest book image to display today while messing around in creative mode with 0.10.1 .  To get the images to show I had to change the setting for home_image from : tolkiencraft:textures\gui\main_title.png  to :  tolkiencraft:textures/gui/main_title.png

looks to be an issue with the path separator.

**Comment by GreatOrator** [comment]
Ahh, so it is an OS specific issue then.  I'll let funwayguy know, maybe there is a work-around for it.
